# Generated by Django 2.2 on 2021-04-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_auto_20210424_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
